* Do neural networks think like geomorphologists?
#+DATE: 2026-07-17
One of the motivating questions for me work, is how can we quantify important but complex patterns in spatial data?  Even relatively complex metrics, can't capture quantitative information from spatial data.  Neural networks are a promising tool to help find and quantify complex spatial patterns, but as an earth scientist, I want to be able to tie machine learning results back to physical theory in a way that enhances our understanding of the natural world.

So as a proof of concept, here's a project that trains a simple neural network to invert topography generated by a simple landscape evolution model, and some insights on how it performs so well, and how it fails.

** the streampower-diffusion model
For our simple generated landscapes we use the streampower diffusion model which generates landscapes with the parameter \(D/K\) as a key control.
#+begin_export html
<details>
<summary>Streampower Diffusion Model Details (click to expand)</summary>
#+end_export

I chose to use landscape evolution models in this project, because I wanted to bypass the issues and complexities with real data.  By using this synthetic data I get to focus on evaluating a neural networks learning of a simple, highly controlled, and well understood system.  Particularly I use the "streampower-diffusion" (SPD) model, which is a very simple and very commonly used model for landscape evolution.  The general idea is that in (some) landscapes there are two primary sources for erosion, overland flow, and hillslope processes.  Erosion due to overland flow is advective, and erosion due to hillslope processes is diffusive.  Geomorphologists have developed some physics based models that quantify this, which I wont go into, but gives us this equation for erosion:
\(\frac{\partial z}{\partial t}=D\nabla^2z - KA^m|\nabla z|^n+U\)
The key things you should know are that \(\frac{\partial z}{\partial t}\) really means the rate of change of elevation (so basically erosion), the first part is hillslope diffusion, and \(D\) controls how effective, or diffusive the landscape is, the second part is fluvial erosion (the streampower law) and \(K\) controls how effective /that/ is, and \(U\) is uplift due to tectonics (assumed to be constant in this system).  In this project we vary D and K, solve this equation numerically to simulate 3 million years of landscape evolution, and then play with the results.

I've mentioned advection and diffusion, and so if you have a certain type of background, your mind might be screaming "Péclet number", and yes, the ratio of advective to diffusive transport is a key control on this system.  In this work we look at the ratio \(D/K\) which can be thought of as a sort of inverse Péclet number.  The reason for \(D/K\) is because of a since aborted attempt to compare with a different data set, but we initially did this work looking at \(K/D\) (this actually comes back a little later) and non-dimensionalized Péclet numbers, and it all works about the same.  By keeping our ratio dimensionalized we avoid having to choose length scales which ends up requiring some justification that really isn't necessary for the core results.
#+begin_export html
</details>
#+end_export

So lets look at how changing \(D/K\) changes the landscape that this model produces:

#+begin_export html
<iframe src="/assets/plotly/06_topography_slider.html" width="100%" height="600" style="border:none;"></iframe>
#+end_export

Ok so it's pretty clear that different landscapes with different \(D/K\) look different in a systematic way. And I bet that you would be able to distinguish between a high and low \(D/K\) landscape, but can you systematically calculate \(D/K\) from bulk topography?  We know that \(D/K\) controls the spacing of valleys [cite:@perronControlsSpacingFirstorder2008], and the drainage density [cite:@howardBadlandMorphologyEvolution1997][cite:@tuckerHillslopeProcessesDrainage1998], but these relationships aren't necessarily one-to-one.  A convolutional neural network can predict numbers, like \(D/K\) and does so by extracting spatial features from the inputs.

** The Neural Network
#+begin_export html
<details>
<summary>Some neural network basics (click to expand)</summary>
#+end_export
The neural network is a function that takes in a 2D single-band input, and produces a single number.  It does so by feeding the input through a series of ``layers'', or simple functions.  The network has four types of layers: convolutions, rectified linear units (ReLU), maximum pooling layers (MaxPool) and Linear layers.  
    -  Convolution :: a convolutional layer contains a window of weights (kernel) which ``sweeps'' over the input.  For each section of input the window overlaps with, the the convolution outputs the weighted sum of the input, with each pixel being modified by the weight overlaying it.  The convolutional layers are the parts of the network that are most sensitive to spatial features.  Traditionally the convolution is thought to be sensitive to a specific feature, and the output is referred to as a ``feature map'', with the value of each pixel of output representing the level of detection of the feature the convolution is sensitive to at that point of the input.
    -  ReLU :: a ReLU (rectified linear unit) is a simple ramp function, that sets the output to zero if below zero, and unchanged if zero or above.  The role of this function is to introduce nonlinearities into the network.  
    -  MaxPool :: This is functionally a resampling layer, that takes an input, divides it into subsets (in this network, cells of 2 by 2 pixels), and returns only the maximum of that subset.  This helps reduce the size of the data and network.
    -  Linear :: These are $n$ by $m$ linear transformations that help reduce the final feature maps into a single number that is interpreted as the $D/K$ ratio.
Each convolution has a number of channels, which is the number of kernels that transform the input.  In the network used in this paper, the first convolutional layer has ten channels, meaning there are ten three-by-three kernels that transform the input into ten different feature maps, or a ten band image.  Each output feature map is then subjected to the ReLU operation, and the maxpooling operation.  This final ten band output is the input to the next set of convolutions.  The second convolutional layer has five-by-five convolutions and 20 channels, meaning that there are 20 distinct kernels, each of which is applied to the entire ten band input.  This means each kernel in this layer is a five-by-five-by-ten window of weights.  Again, these 20 outputs are subjected to ReLU and maxpooling.  The final convolutional/ReLU/MaxPool layer is a 20 band seven-by-seven convolution.  This 20 band 2D output is flattened into a (very long) 1D vector.  This is what is passed to a series of linear transformations and ReLU layers to become a single number.  Specifically, it is passed through a linear transformation with 100 outputs and subjected to a ReLU activation layer.  This is then passed to a linear transformation and ReLU with 10 outputs, and finally a linear transformation that produces a single number output that is interpreted as the network's inferred \(D/K\) value for the given input.

#+begin_export html
</details>
#+end_export
We use a pretty basic architecture with three convolution layers followed by three linear layers.  See [[https://jrymart.github.io/agu2024][this page]] for a network diagram of the neural network (it includes feature maps and activation maximization images.
** The Question
So here's the question: *Can a neural network extract \(D/K\) from bulk topography?  And if so, does it use geomorphically meaningful features to do so?*
Lets run thousands of models and see if a neural network can invert them.




** The Answer
It's yes (to the first part).
#+begin_export html
<iframe src="/assets/plotly/01_predicted_vs_true.html" width="100%" height="600" style="border:none;"></iframe>
#+end_export
There is some serious spread at low \(D/K\) values but theres a lot less data there just due to how I chose parameter spacing.  Also look above at how the landscapes change as \(D/K\) is lowered, they get more and more dissected.  It's possible that landscapes are really really similar in that low \(D/K\) range, where the scale of dissection is smaller than the scale of my model resolution.

Still we have a normalized root mean squared error of *0.0207* which I think is good enough to say a neural network can extract \(D/K\) from bulk topography.  So is it doing so in a geomorphically meaningful way?  /Is it thinking like a geomorphologist?/


