* neural-spd-inversion
#+begin_export html
layout: page
title: neural-spd-inversion
importance: 1
category: work
#+end_export

One of the motivating questions for me work, is how can we quantify important but complex patterns in spatial data?  Even relatively complex metrics, can't capture quantative information from spatial data.  Neural networks are a promising tool to help find and quantify complex spatial patterns, but as an earth scientist, I want to be able to tie machine learning results back to physical theory in a way that enhances our understanding of the natural world.

So as a proof of concept, here's a project that trains a simple neural network to invert topography generated by a simple landscape evolution model, and some insights on how it performs so well, and how it fails.

** the streampower-diffusion model
/This is the basics of the landscape evolution model used to generate data for this study, if all you care about is the neural network stuff, you can skip this.  It will be brought up again as I tie back some results to this model. - Jo/
I chose to use landscape evolution models in this project, because I wanted to bypass the issues and complexities with real data.  By using this synthetic data I get to focus on evaluating a neural networks learning of a simple, highly controlled, and well understood system.  Particularly I use the "streampower-diffusion" (SPD) model, which is a very simple and very commonly used model for landscape evolution.  The general idea is that in (some) landscapes there are two primary sources for erosion, overland flow, and hillslope processes.  Erosion due to overland flow is advective, and erosion due to hillslope processes is diffusive.  Geomorphologists have developed some physics based models that quantify this, which I wont go into, but gives us this equation for erosion:
\(\frac{\partial z}{\partial t}=D\nabla^2z - KA^m|\nabla z|^n+U\)
The key things you should know are that \(\frac{\partial z}{\partial t}\) really means the rate of change of elevation (so basically erosion), the first part is hillslope diffusion, and \(D\) controls how effective, or diffusive the landscape is, the second part is fluvial erosion (the streampower law) and \(K\) controls how effective /that/ is, and \(U\) is uplift due to tectonics (assumed to be constant in this system).  In this project we vary D and K, solve this equation numerically to simulate 3 million years of landscape evolution, and then play with the results.

I've mentioned advection and diffusion, and so if you have a certain type of background, your mind might be screaming "Péclet number", and yes, the ratio of advective to diffusive transport is a key control on this system.  In this work we look at the ratio \(D/K\) which can be thought of as a sort of inverse Péclet number.  The reason for \(D/K\) is because of a since aborted attempt to compare with a different data set, but we initially did this work looking at \(K/D\) (this actually comes back a little later) and non-dimensionalized Péclet numbers, and it all works about the same.  By keeping our ratio dimensionalized we avoid having to choose length scales which ends up requiring some justification that really isn't necessary for the core results.

So lets look at how changing \(D/K\) changes the landscape that this model produces:
#+begin_export html
{% include _includes/plotly/06_topography_slider.html %}
#+end_export
